defaults:
  - model_checkpoint_last
  - model_summary
  - fancy_progress_bar
  - early_stopping

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
# early_stopping:
#   monitor: "val/acc"
#   patience: 100
#   mode: "max"

early_stopping:
  monitor: "val/acc" # quantity to be monitored, must be specified !!!
  min_delta: 1e-3
  mode: "max"
  divergence_threshold: 0.5
