_target_: ptame.models.components.rand_model.cascading_random_model
model:
  _target_: torchvision.models.resnet50
  weights: "IMAGENET1K_V1"
rand_model:
  _target_: torchvision.models.resnet50
layer_key: layer1
random_before: true
random_after: false
