# @package _global_

# uses only 1% of the training data and 5% of validation/test data
defaults:
  - default

trainer:
  max_epochs: 1
  limit_train_batches: 0.1
  val_check_interval: 0.5
  limit_val_batches: 16
  limit_test_batches: 16
